development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: davidmadar
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: davidmadar
  password: 

